### ISSUE TITLE
Redmatrix guid breaks posting

### ISSUE THREAD

**Issue by jpope777** [marekjm/diaspy#23]
Seems that anytime there is a post from a redmatrix site among the recent posts in my stream, diaspy is unable to post to my stream. I assume it's due to the messed up post guid that redmatrix uses. 

Traceback:

```
Traceback (most recent call last):
  File "/home/jpope/bin/diaspost", line 9, in <module>
stream = diaspy.streams.Stream(d)
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/streams.py", line 34, in __init__
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/streams.py", line 122, in fill
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/streams.py", line 66, in _obtain
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/streams.py", line 66, in <listcomp>
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/models.py", line 337, in __init__
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/models.py", line 369, in _fetchdata
diaspy.errors.PostError: 404: could not fetch data for post: 97a0f4d1ef91597958eeedc569b209921addb55e6fd0e4ddc533fe4cfc744a2b@parlementum.red
```

Not sure this is really a bug with diaspy or me just being frustrated with the redmatrix guid...

**Comment by marekjm** [comment]
Noted.

**Comment by redmatrix** [comment]
redmatrix uses real globally unique identifiers (guids), not just "use a large random number and pray". There are best practice documents for generating these in a decentralised network going back 30 years or more; basically a unique local identifier @ domainname, documented in RFC2822. 

The dots in the domain name mess up Ruby's document type detection as it knows how to generate a document with .json but not .com - the solution is to urlencode these whenever they are used in a path component of a URL. (Replace '@' with %40 and '.' with %2E ). Probably a good idea to escape any URL special chars; because redmatrix and friendica both provide plugins to communicate with other systems who may generate other guid formats, and this will save you from doing it again if you encounter yet another guid format in the future.  Diaspora itself does not use the guid in URLs (although they did some time ago so it is still supported), so this issue usually only shows up in third party Diaspora toolkits. 

I'm not deeply experienced in python but it looks like this transformation could be applied at models.py:366
