### ISSUE TITLE
Notifications: AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Flashwalker** [marekjm/diaspy#31]
Don't know what happened, but now getting of Notifications fails with:

```
$ python3  
Python 3.4.3 (default, Sep 14 2016, 12:46:27)  
[GCC 4.8.4] on linux  
Type "help", "copyright", "credits" or "license" for more information.  
>>> import diaspy  
>>> c = diaspy.connection.Connection(pod='https://russiandiaspora.org', username='***', password='***')  
>>> c.login()  
uKkjnJi8Sq76I7nxJpeRmovMdICRn+lPQZUrsVjQgvfxs06mbpgVQ6S24cw4k5o1y3JLFGqCwsCoY1Ch4xJatQ==  
>>> n = diaspy.notifications.Notifications(c)  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/diaspy/notifications.py", line 18, in __init__
    self._notifications = self.get()
  File "/usr/local/lib/python3.4/dist-packages/diaspy/notifications.py", line 50, in get
    return [Notification(self._connection, n) for n in notifications]
  File "/usr/local/lib/python3.4/dist-packages/diaspy/notifications.py", line 50, in <listcomp>
    return [Notification(self._connection, n) for n in notifications]
  File "/usr/local/lib/python3.4/dist-packages/diaspy/models.py", line 158, in __init__
    self.type = list(data.keys())[0]
AttributeError: 'str' object has no attribute 'keys'  
```

diaspy version: 0.5.1 from pypi

**Comment by marekjm** [comment]
Jinkies! Looks like `data` used to be a `dict` but now it's a string, strange... What version of Diaspora\* is the pod you tried to fetch the notifications from running?

**Comment by Flashwalker** [comment]
0.6.3.0-p1702cc1c  
https://github.com/diaspora/diaspora/blob/1702cc1c86be6a52922117ebafb5d0b1521a5ab7/Changelog.md

**Comment by marekjm** [comment]
Should work now.

**Comment by Flashwalker** [comment]
Yep, it works!
