### ISSUE TITLE
Cannot login: diaspy.connection.LoginError

### ISSUE THREAD

**Issue by foreignperson** [marekjm/diaspy#40]
i tried this: 
`c = diaspy.connection.Connection(pod='https://spyurk.am', username='username', password='password')`

and it returned this:
`
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/diaspy/connection.py", line 42, in __init__
    self._setlogin(username, password)
  File "/app/.heroku/python/lib/python3.6/site-packages/diaspy/connection.py", line 116, in _setlogin
    'authenticity_token': self._fetchtoken()}
  File "/app/.heroku/python/lib/python3.6/site-packages/diaspy/connection.py", line 166, in _fetchtoken
    token = self._token_regex.search(request.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.heroku/python/lib/python3.6/site-packages/diaspy/connection.py", line 44, in __init__
    raise LoginError('cannot create login data (caused by: {0}'.format(e))
diaspy.connection.LoginError: cannot create login data (caused by: 'NoneType' object has no attribute 'group'
`

i don't know why it doesn't work, please help

**Comment by CYBERDEViLNL** [comment]
If you installed `diaspy` through PiPy please remove it and install `diaspy-api` or just install the latest master from GitHub. See https://github.com/marekjm/diaspy/issues/17

**Comment by foreignperson** [comment]
oh, thanks. it worked:)
